name: Shef
description: ""
baseurl:
url: http://www.shef.io
social:
  github: #projectshef
  email: wsheet@shef.io
  facebook:
  twitter: projectshef
  instagram: projectshef
  tumblr:
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
